Matrix descomposition:

We can write a matrix as the product of:
- A matrix of its eigenvectors: V
- A diagonal matrix with its eigenvalues: lambda 
- Inverse of V: V_inv 

In [2]:
import numpy as np

In [3]:
A = np.array([[3,2],[4,1]])

In [4]:
eigenvalues, eigenvectors =  np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[ 5. -1.]
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [5]:
A_calc = eigenvectors.dot(np.diag(eigenvalues)).dot(np.linalg.inv(eigenvectors))
print(A_calc)

[[3. 2.]
 [4. 1.]]


If a matrix is real and symetric (A == A.T), we can write this matrix as the product of:
- A matrix of its eigenvectors: V
- A diagonal matrix with its eigenvalues: lambda 
- V transposed: V.T 

Calculating the transpose more computationally efficient than calculating the inverse

In [7]:
A = np.array([[3,2],[2,3]])

print(A)
print(A == A.T)

[[3 2]
 [2 3]]
[[ True  True]
 [ True  True]]


In [9]:
eigenvalues, eigenvectors =  np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[5. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [11]:
A_calc = eigenvectors.dot(np.diag(eigenvalues)).dot(eigenvectors.T)
print(A_calc)

[[3. 2.]
 [2. 3.]]
