Useful concepts:
- Orthogonal matrix: a matrix that its vectors are orthonormal

Single values descomposition it's used for non-square matrices

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[3,4,5]])

In [6]:
U, D, V = np.linalg.svd(A)
print(U)
print(np.diag(D))
print(V)

[[-0.46410668  0.88577931]
 [-0.88577931 -0.46410668]]
[[7.97638869 0.        ]
 [0.         0.61418515]]
[[-0.39133557 -0.5605708  -0.72980603]
 [-0.8247362  -0.13817999  0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]
