When a matrix has no an inverse, we can calculate its pseudoinverse (A(pse)) to get:

A(pse) * A is almost equal to I

But if a calculate A * A(pse), the result is quite different from I

How to get the pseudoinverse?

A(pse) = V * D(pse) * U.T

In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True)

In [4]:
A = np.array([[2,3], [5,7], [11,13]])

The Moore Penrose Pseudoinverse check 4 conditions to affirm that exists only one pseudoinverse. (We will not study this conditions during this course)

In [5]:
U,D,V = np.linalg.svd(A)
print(A)
print(U)
print(D)
print(V)

[[ 2  3]
 [ 5  7]
 [11 13]]
[[-0.18499741 -0.47276624 -0.86154979]
 [-0.44249308 -0.74271297  0.50257071]
 [-0.87748267  0.4742041  -0.07179582]]
[19.40321383  0.71783924]
[[-0.63055377 -0.77614557]
 [ 0.77614557 -0.63055377]]


In [10]:
D_pse = np.zeros((A.shape[0], A.shape[1])).T

D_pse values to replace

In [12]:
print(D_pse[:D.shape[0], :D.shape[0]])

[[0. 0.]
 [0. 0.]]


Values to save in D_pse

In [13]:
print(np.linalg.inv(np.diag(D)))

[[0.05153785 0.        ]
 [0.         1.39306957]]


D_pse

In [14]:
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

[[0.05153785 0.         0.        ]
 [0.         1.39306957 0.        ]]


A_pse

In [16]:
A_pse = V.T.dot(D_pse).dot(U.T)
A_pse

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [17]:
A_pse_calc = np.linalg.pinv(A)
A_pse_calc

array([[-0.50515464, -0.78865979,  0.54123711],
       [ 0.42268041,  0.67010309, -0.3814433 ]])

In [19]:
print(A_pse_calc.dot(A))

[[ 1. -0.]
 [ 0.  1.]]


But if I change the order of the elements:

In [26]:
print(A.dot(A_pse_calc))

[[ 0.25773196  0.43298969 -0.06185567]
 [ 0.43298969  0.74742268  0.03608247]
 [-0.06185567  0.03608247  0.99484536]]


In [27]:
np.set_printoptions(suppress=False)

In [22]:
print(A_pse_calc.dot(A))

[[ 1.00000000e+00 -8.88178420e-16]
 [ 2.66453526e-15  1.00000000e+00]]


Another type of pseudoinverse:

(Numpy use the Moore Penrose Pseudoinverse because is more efficient and accurate)

In [28]:
A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse)
print(A_pse_2)

[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
[[-0.50515464 -0.78865979  0.54123711]
 [ 0.42268041  0.67010309 -0.3814433 ]]
