In [2]:
import numpy as np

In [2]:
myList=[1,2,3,4,5,6,7,8,9]
print(myList)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
npList = np.array(myList)

In [5]:
type(npList)

numpy.ndarray

In [9]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(matrix)
type(matrix)

numpy.ndarray

In [10]:
npList[2]

3

Numpy makes array values operable

In [12]:
npList[0] + npList[1]

10

How to access to the values through their indexes

In [13]:
matrix[0,0] + matrix[2,2]

10

Slicing: this function not includes the last index. If I don't write the initial index, this function takes index 0. If I don't write the final index, this function takes the last index. I can call this function without specifying the initial index and the final index.

In [14]:
npList[0:2]

array([1, 2])

In [15]:
npList[::3]

array([1, 4, 7])

In [16]:
npList[-3]

7

In [18]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

In [21]:
npList.dtype

dtype('int64')

In [25]:
floatArray=np.array([1,2,3],dtype="float64")
floatArray.dtype

dtype('float64')

In [26]:
npList.astype(np.float64)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
intArray=np.array([0,1])
intArray.astype(np.bool_)
intArray

array([0, 1])

In [31]:
intArray=np.array([0,1])
intArray.astype(np.string_)
intArray

array([0, 1])

Every array only has one data type

In [32]:
intArray=np.array(['0','1'])
intArray.astype(np.int8)
intArray

array(['0', '1'], dtype='<U1')

Dimensions
![array-dimensions.png](../images/array-dimensions.png)

In [33]:
scalar=np.array(42)
scalar.ndim

0

In [34]:
scalar=np.array([42])
scalar.ndim

1

Add or remove dimensions:

In [42]:
array=np.array([1,2,3],ndmin=10)
print(array)
array_2=np.squeeze(array)
print(array_2)

[[[[[[[[[[1 2 3]]]]]]]]]]
[1 2 3]


In [39]:
array = np.array([1,2,3])
np.expand_dims(array,axis=0) # 0 is rows, 1 is columns

array([[1, 2, 3]])

Creating Arrays

In [44]:
array = np.arange(0,10,2)
array

array([0, 2, 4, 6, 8])

In [48]:
array = np.zeros((10,5))
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
array = np.ones((10,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
array = np.linspace(0,5,10)
array

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [52]:
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.rand(4,3)

array([[0.92425731, 0.43590147, 0.44264872],
       [0.54046639, 0.82440454, 0.59921056],
       [0.13203061, 0.37740038, 0.20595722],
       [0.9219402 , 0.77586076, 0.68913311]])

In [55]:
np.random.randint(1,15,(2,3))

array([[14,  7,  1],
       [12, 10,  9]])

In [57]:
array = np.random.randint(1,15,(2,3))
array.shape

(2, 3)

In [ ]:
array = np.random.randint(1,15,(2,3))
array.reshape(1,6)

In [58]:
array = np.random.randint(1,15,(2,3))
print(array)
print(np.reshape(array,(3,2),'C')) #It's preferable to use this, because Python is build in C 
print(np.reshape(array,(3,2),'F'))
print(np.reshape(array,(3,2),'A')) #Better storage in my system, C or F

[[ 6  1  6]
 [14  3 14]]
[[ 6  1]
 [ 6 14]
 [ 3 14]]
[[ 6  3]
 [14  6]
 [ 1 14]]


In [64]:
array = np.random.randint(1,15,(2,3))
print(array)
print(array.max(1))
print(array.max(0))
print(array.argmax()) #Return the index
print(array.argmax(1)) #Return the index
print(array.argmax(0)) #Return the index
print(array.min(1))
print(array.min(0))
print(array.argmin()) #Return the index
print(array.argmin(1)) #Return the index
print(array.argmin(0)) #Return the index
print(array.ptp()) #Max - Min
print(array.ptp(0)) #Max - Min
print(array.ptp(1)) #Max - Min
print(np.percentile(array,0)) #25, 50 or 100
print(np.median(array)) #Percentile 50
print(np.median(array,0))
print(np.median(array,1))
print(np.sort(array))
print(np.std(array))
print(np.var(array))
print(np.mean(array))

[[ 9  9  9]
 [12  5  3]]
[ 9 12]
[12  9  9]
3
[0 0]
[1 0 0]
[9 3]
[9 5 3]
5
[0 2]
[0 1 1]
9
[3 4 6]
[0 9]
3.0
9.0
[10.5  7.   6. ]
[9. 5.]
[[ 9  9  9]
 [ 3  5 12]]
2.9674156357941426
8.805555555555555
7.833333333333333


In [71]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])
b = np.expand_dims(b,axis=0)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b.T),axis=1)) #T=Transposed

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


Copy

In [3]:
array=np.arange(0,11)
#slicedarray=array[0:6] #It is a memory reference. Changes in slicedarray will affect the original array
slicedarray=array[0:6].copy()
slicedarray[:]=0
print(array)
print(slicedarray)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0]


Conditions

In [16]:
array=np.linspace(1,10,10,dtype='int8')
print(array)
condition=array>5
print(condition)
print(array[condition])
print(array[(array>5) & (array<9)])
array[(array>5)] = 99
print(array)
print(array[array >= 99])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7 8]
[ 1  2  3  4  5 99 99 99 99 99]
[99 99 99 99 99]


Operations

In [17]:
list = [1,2]
list * 2

[1, 2, 1, 2]

In [23]:
array = np.arange(0,10)
array2 = array.copy()
print(array2 * 2)
print(array2 + 2)
print(array2 / 2)

print(np.array([1,2,3])*np.array([4,5,6]))

[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 4 10 18]


In [26]:
matrix=array.reshape(2,5)
matrix2=matrix.copy()
print(matrix+matrix2)
print(np.matmul(matrix,matrix2.T))
print(matrix @ matrix2.T) #Is the same as matmul

[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[ 30  80]
 [ 80 255]]
