In [2]:
import numpy as np

In [5]:
scalar = 5.678

vector = np.array([1,2,3])

matrix = np.array([[1,2,3],[4,5,6]])

tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]]
])

In [7]:
# Broadcasting: repeats the vector to match the shape of the matrix
A = matrix + vector
A

array([[2, 4, 6],
       [5, 7, 9]])

In [8]:
print(vector+scalar)
print(vector+[5.678,5.678,5.678])

[6.678 7.678 8.678]
[6.678 7.678 8.678]
