In [1]:
import numpy as np

Identity matrix

In [3]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
vector = np.array([[2],[3],[5],[7]])

In [6]:
print(identity.dot(vector))

[[2.]
 [3.]
 [5.]
 [7.]]


Inverse matrix

In [8]:
A = np.array(([1,0,1],[0,1,1],[-1,1,1]))
inv_A = np.linalg.inv(A)

print(A.dot(inv_A))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Singular matrix

In [11]:
B = np.array(([1,1],[1,1]))
inv_B = np.linalg.inv(B)

LinAlgError: Singular matrix