In [1]:
import numpy as np

Properties:
    (A.B)t = Bt . At
    (A.B)tt = A.B

In [2]:
A=np.array([[2,3],[5,7],[11,13]])
B=np.array([[1,3],[2,1]])

In [3]:
print(A)
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]]
[[1 3]
 [2 1]]


In [6]:
AB_t = A.dot(B).T
B_tA_b = B.T.dot(A.T)

print(AB_t)
print(B_tA_b)

[[ 8 19 37]
 [ 9 22 46]]
[[ 8 19 37]
 [ 9 22 46]]
