In [1]:
import numpy as np

In [2]:
vector = np.array([1,2,3,4,5])
matrix = np.diag(vector)
print(matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Examples of non-square diagonal matrix

In [5]:
print(matrix[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [6]:
print(matrix[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [7]:
A = np.diag([2,3,4,5])
print(A)

vector=np.array([1,1,1,1])
print(vector)

print(A.dot(vector.T))

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]
[1 1 1 1]
[2 3 4 5]


In [10]:
A_inv = np.diag([1/2,1/3,1/4,1/5]) # 1/(diagonal element)
print(A_inv)
print(np.linalg.inv(A))

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]
[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [9]:
identity_matrix = A.dot(A_inv)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


A matrix is symmetric when A = A.T

For symmetric matrices:
    (AB).T = B.T A.T = B A