In [2]:
import numpy as np

In [3]:
scalar = 5.678

vector = np.array([1,2,3])

matrix = np.array([[1,2,3],[4,5,6]])

tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]]
])

In [4]:
A = matrix * vector
print(A) # Broadcasting

B = matrix.dot(vector)
# B = np.dot(matrix, vector)
print(B)

[[ 1  4  9]
 [ 4 10 18]]
[14 32]


In [5]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A.shape)

B = np.array([[2,3],[5,7],[11,13]])
print(B.shape)

(4, 3)
(3, 2)


In [6]:
print(A.dot(B))

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [7]:
print(B.dot(A))

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)