In [2]:
import numpy as np

In [3]:
A=np.array([[2,3],[5,7],[11,13]])
B=np.array([[1,3],[2,1]])
C=np.array([[3,1],[4,2]])

In [12]:
#Properties
#Associative: Ax(BxC) = (AxB)xC
print(A.dot(B.dot(C)))
print(A.dot(B).dot(C))
print(A.dot(B.dot(C))==A.dot(B).dot(C))

[[ 60  26]
 [145  63]
 [295 129]]
[[ 60  26]
 [145  63]
 [295 129]]
[[ True  True]
 [ True  True]
 [ True  True]]


In [8]:
#Distributive: Ax(B+C) = AxB+AxC
print(A.dot(B+C))
print(A.dot(B)+A.dot(C))

[[ 26  17]
 [ 62  41]
 [122  83]]
[[ 26  17]
 [ 62  41]
 [122  83]]


In [15]:
#Commutative: AxB = BxA

D=np.array([[1,2],[3,4]])
E=np.array([[5,6],[7,8]])

#It is NOT commutative
print(D.dot(E))
print(E.dot(D))

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [17]:
# It is commutative only for vectors

D=np.array([[1,2]])
E=np.array([[5,6]])

print(D.dot(E.T))
print(E.dot(D.T))

[[17]]
[[17]]
