In [2]:
import numpy as np

In [8]:
scalar = 5.678

vector = np.array([1,2,3,4])

matrix = np.array([[1,2,3],[4,5,6]])

tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]]
])

In [4]:
#Scalars has no transposed
scalar.T

AttributeError: 'float' object has no attribute 'T'

In [9]:
vector_t = vector.T
print(vector_t)

matrix_t = matrix.T
print(matrix_t)

tensor_t = tensor.T
print(tensor_t)

[1 2 3 4]
[[1 4]
 [2 5]
 [3 6]]
[[[ 1 11]
  [ 4 14]
  [ 7 17]]

 [[ 2 12]
  [ 5 15]
  [ 8 18]]

 [[ 3 13]
  [ 6 16]
  [ 9 19]]]


In [10]:
#Transposed of transposed matrix is the original matrix
matrix_t_t = matrix_t.T
print(matrix_t_t)

[[1 2 3]
 [4 5 6]]


In [11]:
#Addition: both matrices must have the same shape
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])

print(A+B)

[[ 8 10 12]
 [14 16 18]]


In [12]:
print(A+scalar)

[[ 6.678  7.678  8.678]
 [ 9.678 10.678 11.678]]
